# Generated by Django 5.0.1 on 2024-01-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('numero_documento', models.BigIntegerField()),
                ('correo', models.CharField(max_length=150)),
                ('telefono', models.BigIntegerField()),
                ('millas', models.IntegerField(blank=True, null=True)),
                ('contraseña', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=64)),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_destino_trajectories', to='horizon.city')),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_origen_trajectories', to='horizon.city')),
            ],
        ),
    ]
